### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-payment#222]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_banking_sepa_direct_debit - By @alexis-via - #270
- [x] account_payment_purchase - By @cubells - #355 
- [x] ~~account_payment_include_draft_move~~ - Removed - By @alexis-via - #270
- [x] ~~account_banking_payment_export~~ > Merged with Odoo's v8 _account_payment_ module in _account_payment_order_ - By @alexis-via - #270
- [x] account_payment_partner - By @alexis-via - #270
- [x] account_payment_transfer_reconcile_batch - By @sergio-teruel - #323 
- [x] ~~account_direct_debit~~ > Merged in _account_payment_order_ - By @alexis-via - #270
- [x] ~~bank_statement_instant_voucher~~ Not needed as there's no voucher now
- [x] account_banking_pain_base - By @alexis-via - #270
- [x] ~~account_voucher_killer~~ Not needed as there's no voucher now
- [x] ~~account_banking_payment_transfer~~ > Merged in _account_payment_order_ - By @alexis-via - #270
- [x] account_banking_sepa_credit_transfer - By @alexis-via - #270
- [x] account_payment_sale - By @alexis-via - #270
- [x] ~~account_payment_sale_stock~~ - Not needed anymore - By @alexis-via - #270
- [x] account_banking_tests - By @alexis-via - #270
- [ ] account_import_line_multicurrency_extension
- [ ] account_payment_mode_term
- [x] account_banking_mandate - By @alexis-via - #270
- [x] account_payment_blocking (included in account_payment_order and https://github.com/OCA/account-invoicing/tree/9.0/account_invoice_blocking)
- [x] portal_payment_mode - By @chienandalu - #387

**Comment by StephanRozendaal** [comment]
I would like to port account_payment_blocking to 9.0, but that module is depending on account_banking_payment_export. The account_banking_payment_export is to be merged with the account_payment module. I found a PR which was closed OCA/account-payment#73, @pedrobaeza mentioning that it needed to be redone. What's the status on this?

**Comment by sbidoul** [comment]
@StephanRozendaal no need to port it: that functionality should be covered by account_payment_order and account_invoice_blocking: https://github.com/OCA/account-invoicing/tree/9.0/account_invoice_blocking

**Comment by pedrobaeza** [comment]
Sorry for not updating this issue. Doing right now.

**Comment by pedrobaeza** [comment]
Closing this issue as most important modules have been already migrated and the 2 remaining ones are marginal features that even can belong to another repository.
