### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-payment#304]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_banking_mandate - By @alexis-via - #305
- [x] account_banking_mandate_sale - By @alexis-via - #305
- [x] account_banking_pain_base - By @alexis-via - #305
- [x] account_banking_sepa_credit_transfer - By @alexis-via - #305
- [x] account_banking_sepa_direct_debit - By @alexis-via - #305
- [x] ~~account_banking_tests~~ Not needed anymore
- [ ] account_import_line_multicurrency_extension
- [ ] account_payment_blocking
- [x] account_payment_mode - By @alexis-via - #305
- [ ] account_payment_mode_term
- [x] account_payment_order - By @alexis-via - #305
- [x] account_payment_partner - By @alexis-via - #305
- [ ] account_payment_purchase - ~~By @GillesTephaneMeyomesse - #352~~ By @Abranes - #492 
- [x] account_payment_sale - By @alexis-via - #305
- [x] account_voucher_killer - By @ovnicraft - #480 
- [ ] bank_statement_instant_voucher
- [x] ~~portal_payment_mode - By @sergio-teruel - #482~~ Not needed in this version
