### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-payment#394]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_banking_mandate - By @etobella - #404 
- [x] account_banking_mandate_sale - By @thinkwelltwd - #565 
- [x] account_banking_pain_base - By @etobella - #405 
- [x] account_banking_sepa_credit_transfer - By @etobella - #406 
- [x] account_banking_sepa_direct_debit - By @etobella - #407 
- [ ] account_payment_blocking
- [ ] account_payment_line_cancel - By @MaxyMoos - #516 
- [x] account_payment_mode - By @etobella - #399 
- [ ] account_payment_mode_term
- [x] account_payment_order - By @etobella - #401 
- [x] account_payment_order_return - By @cubells - #506 
- [x] account_payment_partner - By @etobella - #400 
- [x] account_payment_purchase - By @cubells - #512 
- [x] account_payment_sale - By @arkostyuk - #434 
- [x] ~~portal_payment_mode~~ Not needed in this version

**Comment by ghost** [comment]
WIP on `account_payment_sale` (#434)

**Comment by cesarsc79** [comment]
Hi

account Payment return import sepa pain

where is it for 11?

**Comment by pedrobaeza** [comment]
Not yet migrated.

**Comment by thinkwelltwd** [comment]
Any chance #565 could get merged?

**Comment by pedrobaeza** [comment]
Main modules have been merged, so I think we can close this.
