### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#964]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_banking_mandate - By @Reyes4711-S73 - #1028
- [x] account_banking_pain_base - By @pedrobaeza - #1087
- [x] account_banking_sepa_credit_transfer - By @dzungtran89 - #990
- [x] account_banking_sepa_direct_debit - By @Reyes4711-S73 - #1029
- [x] account_payment_mode - By @ThomasBinsfeld - #968
- [x] account_payment_order - By @wpichler / @pedrobaeza - #1056
- [x] account_payment_order_grouped_output - By @ferran-S73 - #1044
- [x] account_payment_order_notification - By @Yadier-Tecnativa - #1095
- [x] account_payment_order_return - By @almumu - #1359
- [ ] account_payment_order_transfer_journal - By @luc-demeyer - #1108
- [x] account_payment_partner - By @ThomasBinsfeld - #969
- [x] account_payment_purchase - By @ramiadavid - #1004
- [x] account_payment_purchase_stock - By @SodexisTeam - #1063
- [x] account_payment_sale - By @atchuthan - #982

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dzungtran89** [comment]
Hello, I will migrate `account_banking_sepa_credit_transfer`

**Comment by ramiadavid** [comment]
Hi @OCA/banking-maintainers
Im working on `account_payment_purchase` #1004

**Comment by JavierIniesta** [comment]
Hi @sbidoul 

I have seen that the `account_payment_sale` addon is already migrated but it is not checked in the list.

**Comment by fgarcia-humanoide** [comment]
[16.0][MIG] account_banking_sepa_direct_debit: Migration to 16.0 #1029

sepa direct debit 16 is being migrated but do not appear in the list as being in process of migration

**Comment by ferran-S73** [comment]
account_banking_mandate_sale https://github.com/OCA/bank-payment/pull/1008

**Comment by vincent-hatakeyama** [comment]
account_payment_order_tier_validation #1161

This was not migrated to 15.0 so it does not appear in the list.

**Comment by Tisho99** [comment]
I'm migrating account_banking_mandate_contact #1233
